name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/MichaelCrowe11/crowecad
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, migrate and restart
        run: |
          export IMAGE_TAG=${GITHUB_SHA}
          docker-compose -f docker-compose.yml -f docker-compose.${ENVIRONMENT}.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.${ENVIRONMENT}.yml up -d --build
          docker tag crowecad ${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          docker-compose -f docker-compose.yml -f docker-compose.${ENVIRONMENT}.yml exec -T crowecad npm run db:migrate
          docker-compose -f docker-compose.yml -f docker-compose.${ENVIRONMENT}.yml restart crowecad
